project:
  type: website

website:
  title: "IS428_VA4BI_Project"
  navbar:
    left: 
      - text: Introduction
        href: introduction.qmd
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    toc: true

editor: visual

